ALTER TABLE pets ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_pets_location ON pets(latitude, longitude);