// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cspwxzwjldyvltaonqpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcHd4endqbGR5dmx0YW9ucXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDY1NTIsImV4cCI6MjA3MTk4MjU1Mn0.207W2-kNf2Bkzdv1ppnhR8d0OWzX9qplvoD3OSoUM98";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});